### ISSUE TITLE
Restructure the project

### ISSUE THREAD

**Issue by Guz013** [LoredDev/ESLit#13]
> Work in progress

Now with the [CLI mostly completed](https://github.com/LoredDev/ESLit/pull/10), it would be better to restructure how the project is made, mostly how the configs are organized.

The current configs are all over the place, and could be more reorganized, focusing on what purpose each has: Core rules, formatting, error preventing, code structure, naming conventions, language-specific, etc.

Also, a preset for projects in a prototyping phase, or multiple different phases, could be created, relaxing rules for faster and easier development. And then the default rules would be used for future refactors.

---
Current steps:

- [x] Rebranding: Change the name of "ESLit" to "ESLegant". Move the CLI and core rules to a "main package", scoped packages will be used for things like frameworks. (#15)
  - [x] Improve/add exported APIs for the CLI package, so it can be used more programmatically on other packages. (#14)
- [ ] Create new configuration files (#16)
  - [x] Formatting & Code style
  - [ ] Naming conventions
  - [x] Error preventing / Strict rules
  - [x] Core rules / plugin setups
  - [x] `error`, `warning`, and `off` variations for each configs
